{
 "cells": [
  {
   "cell_type": "markdown",
   "id": "e2f327e7",
   "metadata": {},
   "source": [
    "# OpenAPI를 이용한 논문, 기사, 글 요약 및 번역\n",
    "\n",
    "https://jehyunlee.github.io/2022/07/02/Python-DS-106-aaicon/\n",
    "\n",
    "### Reference\n",
    "\n",
    "```\n",
    "이제현, 유시현, 김창기, 김현구, \"Open API를 활용한 고속 논문 분석\",\n",
    "실용인공지능학회지 vol.1 p.9, 2022\n",
    "```"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "df051431",
   "metadata": {},
   "source": [
    "## API 키 발급\n",
    "\n",
    "- RapidAPI : https://rapidapi.com/developer/new\n",
    "- 네이버 : https://developers.naver.com/apps/#/register?api=ppg_n2mt"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 28,
   "id": "b204963a",
   "metadata": {},
   "outputs": [],
   "source": [
    "rapidapi_key = 'YOUR_API_KEY_HERE'\n",
    "naver_client_id = 'YOUR_API_KEY_HERE'\n",
    "naver_client_secret = 'YOUR_API_KEY_HERE'"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "f74b1efd",
   "metadata": {},
   "source": [
    "# TLDRThis\n",
    "\n",
    "- https://rapidapi.com/tldrthishq-tldrthishq-default/api/tldrthis/\n",
    "\n",
    "---\n",
    "\n",
    "## 요약의 종류\n",
    "\n",
    "1. Abstractive(Human-like) summarization\n",
    "\n",
    "> Abstractive summarization(생성 요약)은 기존 Input text를 그대로 인용하지 않고, 기존의 내용을 새롭게 re-phrasing 하여 Summary를 생성하는 요약 모델입니다.\n",
    "\n",
    "2. Extractive summarization\n",
    "\n",
    "> 반면에 Extractive summarization(추출 요약)은 기존 Input text에 존재하는 중요한 단어를 그대로 사용하여 Summary를 생성하는 요약 모델입니다.\n",
    "\n",
    "출처 : https://supkoon.tistory.com/40"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "id": "69898271",
   "metadata": {},
   "outputs": [],
   "source": [
    "import requests\n",
    "from pprint import pprint"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "61573ca4",
   "metadata": {},
   "source": [
    "### 예시 논문\n",
    "\n",
    "Attention Is All You Need\n",
    "- 페이지 : https://arxiv.org/abs/1706.03762\n",
    "- 본문(pdf) : https://arxiv.org/pdf/1706.03762.pdf"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "f600ad29",
   "metadata": {},
   "source": [
    "## 요약"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 29,
   "id": "c8a7b18a",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "{'article_abstract': 'The dominant sequence transduction models are based on '\n",
      "                     'complex recurrent or convolutional neural networks that '\n",
      "                     'include an encoder and a decoder. The best performing '\n",
      "                     'models also connect the encoder and decoder through an '\n",
      "                     'attention mechanism. We propose a new simple network '\n",
      "                     'architecture, the Transformer, based solely on attention '\n",
      "                     'mechanisms, dispensing with recurrence and convolutions '\n",
      "                     'entirely. Experiments on two machine translation tasks '\n",
      "                     'show these models to be superior in quality while being '\n",
      "                     'more parallelizable and requiring significantly less '\n",
      "                     'time to train. Our model achieves 28.4 BLEU on the WMT '\n",
      "                     '2014 Englishto-German translation task, improving over '\n",
      "                     'the existing best results, including ensembles, by over '\n",
      "                     '2 BLEU. On the WMT 2014 English-to-French translation '\n",
      "                     'task, our model establishes a new single-model '\n",
      "                     'state-of-the-art BLEU score of 41.8 after training for '\n",
      "                     '3.5 days on eight GPUs, a small fraction of the training '\n",
      "                     'costs of the best models from the literature. We show '\n",
      "                     'that the Transformer generalizes well to other tasks by '\n",
      "                     'applying it successfully to English constituency parsing '\n",
      "                     'both with large and limited training data. * Equal '\n",
      "                     'contribution. Listing order is random. Jakob proposed '\n",
      "                     'replacing RNNs with self-attention and started the '\n",
      "                     'effort to evaluate this idea. Ashish, with Illia, '\n",
      "                     'designed and implemented the first Transformer models '\n",
      "                     'and has been crucially involved in every aspect of this '\n",
      "                     'work. Noam proposed scaled dot-product attention, '\n",
      "                     'multi-head attention and the parameter-free position '\n",
      "                     'representation and became the other person involved in '\n",
      "                     'nearly every detail. Niki designed, implemented, tuned '\n",
      "                     'and evaluated countless model variants in our original '\n",
      "                     'codebase and tensor2tensor. Llion also experimented with '\n",
      "                     'novel model variants, was responsible for our initial '\n",
      "                     'codebase, and efficient inference and visualizations. '\n",
      "                     'Lukasz and Aidan spent countless long days designing '\n",
      "                     'various parts of and implementing tensor2tensor, '\n",
      "                     'replacing our earlier codebase, greatly improving '\n",
      "                     'results and massively accelerating our research. † Work '\n",
      "                     'performed while at Google Brain. ‡ Work performed while '\n",
      "                     'at Google Research.',\n",
      " 'article_authors': ['Ashish  Vaswani',\n",
      "                     'Noam  Shazeer',\n",
      "                     'Google  Brain',\n",
      "                     'Niki  Parmar',\n",
      "                     'Jakob  Uszkoreit',\n",
      "                     'Llion  Jones',\n",
      "                     'Aidan N Gomez',\n",
      "                     'Łukasz  Kaiser'],\n",
      " 'article_html': None,\n",
      " 'article_image': None,\n",
      " 'article_pub_date': '6 Dec 2017',\n",
      " 'article_text': 'The dominant sequence transduction models are based on '\n",
      "                 'complex recurrent or convolutional neural networks that '\n",
      "                 'include an encoder and a decoder. The best performing models '\n",
      "                 'also connect the encoder and decoder through an attention '\n",
      "                 'mechanism. We propose a new simple network architecture, the '\n",
      "                 'Transformer, based solely on attention mechanisms, '\n",
      "                 'dispensing with recurrence and convolutions entirely. '\n",
      "                 'Experiments on two machine translation tasks show these '\n",
      "                 'models to be superior in quality while being more '\n",
      "                 'parallelizable and requiring significantly less time to '\n",
      "                 'train. Our model achieves 28.4 BLEU on the WMT 2014 '\n",
      "                 'Englishto-German translation task, improving over the '\n",
      "                 'existing best results, including ensembles, by over 2 BLEU. '\n",
      "                 'On the WMT 2014 English-to-French translation task, our '\n",
      "                 'model establishes a new single-model state-of-the-art BLEU '\n",
      "                 'score of 41.8 after training for 3.5 days on eight GPUs, a '\n",
      "                 'small fraction of the training costs of the best models from '\n",
      "                 'the literature. We show that the Transformer generalizes '\n",
      "                 'well to other tasks by applying it successfully to English '\n",
      "                 'constituency parsing both with large and limited training '\n",
      "                 'data. * Equal contribution. Listing order is random. Jakob '\n",
      "                 'proposed replacing RNNs with self-attention and started the '\n",
      "                 'effort to evaluate this idea. Ashish, with Illia, designed '\n",
      "                 'and implemented the first Transformer models and has been '\n",
      "                 'crucially involved in every aspect of this work. Noam '\n",
      "                 'proposed scaled dot-product attention, multi-head attention '\n",
      "                 'and the parameter-free position representation and became '\n",
      "                 'the other person involved in nearly every detail. Niki '\n",
      "                 'designed, implemented, tuned and evaluated countless model '\n",
      "                 'variants in our original codebase and tensor2tensor. Llion '\n",
      "                 'also experimented with novel model variants, was responsible '\n",
      "                 'for our initial codebase, and efficient inference and '\n",
      "                 'visualizations. Lukasz and Aidan spent countless long days '\n",
      "                 'designing various parts of and implementing tensor2tensor, '\n",
      "                 'replacing our earlier codebase, greatly improving results '\n",
      "                 'and massively accelerating our research. † Work performed '\n",
      "                 'while at Google Brain. ‡ Work performed while at Google '\n",
      "                 'Research. Introduction Recurrent neural networks, long '\n",
      "                 'short-term memory [13] and gated recurrent [7] neural '\n",
      "                 'networks in particular, have been firmly established as '\n",
      "                 'state of the art approaches in sequence modeling and '\n",
      "                 'transduction problems such as language modeling and machine '\n",
      "                 'translation [35, 2, 5] . Numerous efforts have since '\n",
      "                 'continued to push the boundaries of recurrent language '\n",
      "                 'models and encoder-decoder architectures [38, 24, 15] . '\n",
      "                 'Recurrent models typically factor computation along the '\n",
      "                 'symbol positions of the input and output sequences. Aligning '\n",
      "                 'the positions to steps in computation time, they generate a '\n",
      "                 'sequence of hidden states h t , as a function of the '\n",
      "                 'previous hidden state h t−1 and the input for position t. '\n",
      "                 'This inherently sequential nature precludes parallelization '\n",
      "                 'within training examples, which becomes critical at longer '\n",
      "                 'sequence lengths, as memory constraints limit batching '\n",
      "                 'across examples. Recent work has achieved significant '\n",
      "                 'improvements in computational efficiency through '\n",
      "                 'factorization tricks [21] and conditional computation [32] , '\n",
      "                 'while also improving model performance in case of the '\n",
      "                 'latter. The fundamental constraint of sequential '\n",
      "                 'computation, however, remains. Attention mechanisms have '\n",
      "                 'become an integral part of compelling sequence modeling and '\n",
      "                 'transduction models in various tasks, allowing modeling of '\n",
      "                 'dependencies without regard to their distance in the input '\n",
      "                 'or output sequences [2, 19] . In all but a few cases [27] , '\n",
      "                 'however, such attention mechanisms are used in conjunction '\n",
      "                 'with a recurrent network. In this work we propose the '\n",
      "                 'Transformer, a model architecture eschewing recurrence and '\n",
      "                 'instead relying entirely on an attention mechanism to draw '\n",
      "                 'global dependencies between input and output. The '\n",
      "                 'Transformer allows for significantly more parallelization '\n",
      "                 'and can reach a new state of the art in translation quality '\n",
      "                 'after being trained for as little as twelve hours on eight '\n",
      "                 'P100 GPUs. Background The goal of reducing sequential '\n",
      "                 'computation also forms the foundation of the Extended Neural '\n",
      "                 'GPU [16] , ByteNet [18] and ConvS2S [9] , all of which use '\n",
      "                 'convolutional neural networks as basic building block, '\n",
      "                 'computing hidden representations in parallel for all input '\n",
      "                 'and output positions. In these models, the number of '\n",
      "                 'operations required to relate signals from two arbitrary '\n",
      "                 'input or output positions grows in the distance between '\n",
      "                 'positions, linearly for ConvS2S and logarithmically for '\n",
      "                 'ByteNet. This makes it more difficult to learn dependencies '\n",
      "                 'between distant positions [12] . In the Transformer this is '\n",
      "                 'reduced to a constant number of operations, albeit at the '\n",
      "                 'cost of reduced effective resolution due to averaging '\n",
      "                 'attention-weighted positions, an effect we counteract with '\n",
      "                 'Multi-Head Attention as described in section 3.2. '\n",
      "                 'Self-attention, sometimes called intra-attention is an '\n",
      "                 'attention mechanism relating different positions of a single '\n",
      "                 'sequence in order to compute a representation of the '\n",
      "                 'sequence. Self-attention has been used successfully in a '\n",
      "                 'variety of tasks including reading comprehension, '\n",
      "                 'abstractive summarization, textual entailment and learning '\n",
      "                 'task-independent sentence representations [4, 27, 28, 22] . '\n",
      "                 'End-to-end memory networks are based on a recurrent '\n",
      "                 'attention mechanism instead of sequencealigned recurrence '\n",
      "                 'and have been shown to perform well on simple-language '\n",
      "                 'question answering and language modeling tasks [34] . To the '\n",
      "                 'best of our knowledge, however, the Transformer is the first '\n",
      "                 'transduction model relying entirely on self-attention to '\n",
      "                 'compute representations of its input and output without '\n",
      "                 'using sequencealigned RNNs or convolution. In the following '\n",
      "                 'sections, we will describe the Transformer, motivate '\n",
      "                 'self-attention and discuss its advantages over models such '\n",
      "                 'as [17, 18] and [9] . Model Architecture Most competitive '\n",
      "                 'neural sequence transduction models have an encoder-decoder '\n",
      "                 'structure [5, 2, 35] . Here, the encoder maps an input '\n",
      "                 'sequence of symbol representations (x 1 , ..., x n ) to a '\n",
      "                 'sequence of continuous representations z = (z 1 , ..., z n '\n",
      "                 '). Given z, the decoder then generates an output sequence (y '\n",
      "                 '1 , ..., y m ) of symbols one element at a time. At each '\n",
      "                 'step the model is auto-regressive [10] , consuming the '\n",
      "                 'previously generated symbols as additional input when '\n",
      "                 'generating the next. The Transformer follows this overall '\n",
      "                 'architecture using stacked self-attention and point-wise, '\n",
      "                 'fully connected layers for both the encoder and decoder, '\n",
      "                 'shown in the left and right halves of Figure 1 , '\n",
      "                 'respectively. Figure 1 : The Transformer -model '\n",
      "                 'architecture. Encoder and Decoder Stacks Encoder: The '\n",
      "                 'encoder is composed of a stack of N = 6 identical layers. '\n",
      "                 'Each layer has two sub-layers. The first is a multi-head '\n",
      "                 'self-attention mechanism, and the second is a simple, '\n",
      "                 'positionwise fully connected feed-forward network. We employ '\n",
      "                 'a residual connection [11] around each of the two '\n",
      "                 'sub-layers, followed by layer normalization [1] . That is, '\n",
      "                 'the output of each sub-layer is LayerNorm(x + Sublayer(x)), '\n",
      "                 'where Sublayer(x) is the function implemented by the '\n",
      "                 'sub-layer itself. To facilitate these residual connections, '\n",
      "                 'all sub-layers in the model, as well as the embedding '\n",
      "                 'layers, produce outputs of dimension d model = 512. Decoder: '\n",
      "                 'The decoder is also composed of a stack of N = 6 identical '\n",
      "                 'layers. In addition to the two sub-layers in each encoder '\n",
      "                 'layer, the decoder inserts a third sub-layer, which performs '\n",
      "                 'multi-head attention over the output of the encoder stack. '\n",
      "                 'Similar to the encoder, we employ residual connections '\n",
      "                 'around each of the sub-layers, followed by layer '\n",
      "                 'normalization. We also modify the self-attention sub-layer '\n",
      "                 'in the decoder stack to prevent positions from attending to '\n",
      "                 'subsequent positions. This masking, combined with fact that '\n",
      "                 'the output embeddings are offset by one position, ensures '\n",
      "                 'that the predictions for position i can depend only on the '\n",
      "                 'known outputs at positions less than i. Attention An '\n",
      "                 'attention function can be described as mapping a query and a '\n",
      "                 'set of key-value pairs to an output, where the query, keys, '\n",
      "                 'values, and output are all vectors. The output is computed '\n",
      "                 'as a weighted sum of the values, where the weight assigned '\n",
      "                 'to each value is computed by a compatibility function of the '\n",
      "                 'query with the corresponding key. Scaled Dot-Product '\n",
      "                 'Attention We call our particular attention \"Scaled '\n",
      "                 'Dot-Product Attention\" (Figure 2 ). The input consists of '\n",
      "                 'queries and keys of dimension d k , and values of dimension '\n",
      "                 'd v . We compute the dot products of the query with all '\n",
      "                 'keys, divide each by √ d k , and apply a softmax function to '\n",
      "                 'obtain the weights on the values. In practice, we compute '\n",
      "                 'the attention function on a set of queries simultaneously, '\n",
      "                 'packed together into a matrix Q. The keys and values are '\n",
      "                 'also packed together into matrices K and V . We compute the '\n",
      "                 'matrix of outputs as: Attention(Q, K, V ) = softmax( QK T √ '\n",
      "                 'd k )V (1) The two most commonly used attention functions '\n",
      "                 'are additive attention [2] , and dot-product '\n",
      "                 '(multiplicative) attention. Dot-product attention is '\n",
      "                 'identical to our algorithm, except for the scaling factor of '\n",
      "                 '1 √ d k . Additive attention computes the compatibility '\n",
      "                 'function using a feed-forward network with a single hidden '\n",
      "                 'layer. While the two are similar in theoretical complexity, '\n",
      "                 'dot-product attention is much faster and more '\n",
      "                 'space-efficient in practice, since it can be implemented '\n",
      "                 'using highly optimized matrix multiplication code. While for '\n",
      "                 'small values of d k the two mechanisms perform similarly, '\n",
      "                 'additive attention outperforms dot product attention without '\n",
      "                 'scaling for larger values of d k [3] . We suspect that for '\n",
      "                 'large values of d k , the dot products grow large in '\n",
      "                 'magnitude, pushing the softmax function into regions where '\n",
      "                 'it has extremely small gradients 4 . To counteract this '\n",
      "                 'effect, we scale the dot products by 1 √ d k . Multi-Head '\n",
      "                 'Attention Instead of performing a single attention function '\n",
      "                 'with d model -dimensional keys, values and queries, we found '\n",
      "                 'it beneficial to linearly project the queries, keys and '\n",
      "                 'values h times with different, learned linear projections to '\n",
      "                 'd k , d k and d v dimensions, respectively. On each of these '\n",
      "                 'projected versions of queries, keys and values we then '\n",
      "                 'perform the attention function in parallel, yielding d v '\n",
      "                 '-dimensional output values. These are concatenated and once '\n",
      "                 'again projected, resulting in the final values, as depicted '\n",
      "                 'in Figure 2 . Multi-head attention allows the model to '\n",
      "                 'jointly attend to information from different representation '\n",
      "                 'subspaces at different positions. With a single attention '\n",
      "                 'head, averaging inhibits this. MultiHead(Q, K, V ) = '\n",
      "                 'Concat(head 1 , ..., head h )W O where head i = Attention(QW '\n",
      "                 'Q i , KW K i , V W V i ) Where the projections are parameter '\n",
      "                 'matrices W Q i ∈ R dmodel×d k , W K i ∈ R dmodel×d k , W V i '\n",
      "                 '∈ R dmodel×dv and W O ∈ R hdv×dmodel . In this work we '\n",
      "                 'employ h = 8 parallel attention layers, or heads. For each '\n",
      "                 'of these we use d k = d v = d model /h = 64. Due to the '\n",
      "                 'reduced dimension of each head, the total computational cost '\n",
      "                 'is similar to that of single-head attention with full '\n",
      "                 'dimensionality. Applications of Attention in our Model The '\n",
      "                 'Transformer uses multi-head attention in three different '\n",
      "                 'ways: • In \"encoder-decoder attention\" layers, the queries '\n",
      "                 'come from the previous decoder layer, and the memory keys '\n",
      "                 'and values come from the output of the encoder. This allows '\n",
      "                 'every position in the decoder to attend over all positions '\n",
      "                 'in the input sequence. This mimics the typical '\n",
      "                 'encoder-decoder attention mechanisms in sequence-to-sequence '\n",
      "                 'models such as [38, 2, 9] . • The encoder contains '\n",
      "                 'self-attention layers. In a self-attention layer all of the '\n",
      "                 'keys, values and queries come from the same place, in this '\n",
      "                 'case, the output of the previous layer in the encoder. Each '\n",
      "                 'position in the encoder can attend to all positions in the '\n",
      "                 'previous layer of the encoder. • Similarly, self-attention '\n",
      "                 'layers in the decoder allow each position in the decoder to '\n",
      "                 'attend to all positions in the decoder up to and including '\n",
      "                 'that position. We need to prevent leftward information flow '\n",
      "                 'in the decoder to preserve the auto-regressive property. We '\n",
      "                 'implement this inside of scaled dot-product attention by '\n",
      "                 'masking out (setting to −∞) all values in the input of the '\n",
      "                 'softmax which correspond to illegal connections. See Figure '\n",
      "                 '2 . Position-wise Feed-Forward Networks In addition to '\n",
      "                 'attention sub-layers, each of the layers in our encoder and '\n",
      "                 'decoder contains a fully connected feed-forward network, '\n",
      "                 'which is applied to each position separately and '\n",
      "                 'identically. This consists of two linear transformations '\n",
      "                 'with a ReLU activation in between. FFN(x) = max(0, xW 1 + b '\n",
      "                 '1 )W 2 + b 2 (2) While the linear transformations are the '\n",
      "                 'same across different positions, they use different '\n",
      "                 'parameters from layer to layer. Another way of describing '\n",
      "                 'this is as two convolutions with kernel size 1. The '\n",
      "                 'dimensionality of input and output is d model = 512, and the '\n",
      "                 'inner-layer has dimensionality d f f = 2048. Embeddings and '\n",
      "                 'Softmax Similarly to other sequence transduction models, we '\n",
      "                 'use learned embeddings to convert the input tokens and '\n",
      "                 'output tokens to vectors of dimension d model . We also use '\n",
      "                 'the usual learned linear transformation and softmax function '\n",
      "                 'to convert the decoder output to predicted next-token '\n",
      "                 'probabilities. In our model, we share the same weight matrix '\n",
      "                 'between the two embedding layers and the pre-softmax linear '\n",
      "                 'transformation, similar to [30] . In the embedding layers, '\n",
      "                 'we multiply those weights by √ d model . Positional Encoding '\n",
      "                 'Since our model contains no recurrence and no convolution, '\n",
      "                 'in order for the model to make use of the order of the '\n",
      "                 'sequence, we must inject some information about the relative '\n",
      "                 'or absolute position of the O(n 2 • d) O(1) O(1) Recurrent '\n",
      "                 'O(n • d 2 ) O(n) O(n) Convolutional O(k • n • d 2 ) O(1) '\n",
      "                 'O(log k (n)) Self-Attention (restricted) O(r • n • d) O(1) '\n",
      "                 'O(n/r) tokens in the sequence. To this end, we add '\n",
      "                 '\"positional encodings\" to the input embeddings at the '\n",
      "                 'bottoms of the encoder and decoder stacks. The positional '\n",
      "                 'encodings have the same dimension d model as the embeddings, '\n",
      "                 'so that the two can be summed. There are many choices of '\n",
      "                 'positional encodings, learned and fixed [9] . In this work, '\n",
      "                 'we use sine and cosine functions of different frequencies: P '\n",
      "                 'E (pos,2i) = sin(pos/10000 2i/dmodel ) P E (pos,2i+1) = '\n",
      "                 'cos(pos/10000 2i/dmodel ) where pos is the position and i is '\n",
      "                 'the dimension. That is, each dimension of the positional '\n",
      "                 'encoding corresponds to a sinusoid. The wavelengths form a '\n",
      "                 'geometric progression from 2π to 10000 • 2π. We chose this '\n",
      "                 'function because we hypothesized it would allow the model to '\n",
      "                 'easily learn to attend by relative positions, since for any '\n",
      "                 'fixed offset k, P E pos+k can be represented as a linear '\n",
      "                 'function of P E pos . We also experimented with using '\n",
      "                 'learned positional embeddings [9] instead, and found that '\n",
      "                 'the two versions produced nearly identical results (see '\n",
      "                 'Table 3 row (E)). We chose the sinusoidal version because it '\n",
      "                 'may allow the model to extrapolate to sequence lengths '\n",
      "                 'longer than the ones encountered during training. Why '\n",
      "                 'Self-Attention In this section we compare various aspects of '\n",
      "                 'self-attention layers to the recurrent and convolutional '\n",
      "                 'layers commonly used for mapping one variable-length '\n",
      "                 'sequence of symbol representations (x 1 , ..., x n ) to '\n",
      "                 'another sequence of equal length (z 1 , ..., z n ), with x i '\n",
      "                 ', z i ∈ R d , such as a hidden layer in a typical sequence '\n",
      "                 'transduction encoder or decoder. Motivating our use of '\n",
      "                 'self-attention we consider three desiderata. One is the '\n",
      "                 'total computational complexity per layer. Another is the '\n",
      "                 'amount of computation that can be parallelized, as measured '\n",
      "                 'by the minimum number of sequential operations required. The '\n",
      "                 'third is the path length between long-range dependencies in '\n",
      "                 'the network. Learning long-range dependencies is a key '\n",
      "                 'challenge in many sequence transduction tasks. One key '\n",
      "                 'factor affecting the ability to learn such dependencies is '\n",
      "                 'the length of the paths forward and backward signals have to '\n",
      "                 'traverse in the network. The shorter these paths between any '\n",
      "                 'combination of positions in the input and output sequences, '\n",
      "                 'the easier it is to learn long-range dependencies [12] . '\n",
      "                 'Hence we also compare the maximum path length between any '\n",
      "                 'two input and output positions in networks composed of the '\n",
      "                 'different layer types. As noted in Table 1 , a '\n",
      "                 'self-attention layer connects all positions with a constant '\n",
      "                 'number of sequentially executed operations, whereas a '\n",
      "                 'recurrent layer requires O(n) sequential operations. In '\n",
      "                 'terms of computational complexity, self-attention layers are '\n",
      "                 'faster than recurrent layers when the sequence length n is '\n",
      "                 'smaller than the representation dimensionality d, which is '\n",
      "                 'most often the case with sentence representations used by '\n",
      "                 'state-of-the-art models in machine translations, such as '\n",
      "                 'word-piece [38] and byte-pair [31] representations. To '\n",
      "                 'improve computational performance for tasks involving very '\n",
      "                 'long sequences, self-attention could be restricted to '\n",
      "                 'considering only a neighborhood of size r in the input '\n",
      "                 'sequence centered around the respective output position. '\n",
      "                 'This would increase the maximum path length to O(n/r). We '\n",
      "                 'plan to investigate this approach further in future work. A '\n",
      "                 'single convolutional layer with kernel width k < n does not '\n",
      "                 'connect all pairs of input and output positions. Doing so '\n",
      "                 'requires a stack of O(n/k) convolutional layers in the case '\n",
      "                 'of contiguous kernels, or O(log k (n)) in the case of '\n",
      "                 'dilated convolutions [18] , increasing the length of the '\n",
      "                 'longest paths between any two positions in the network. '\n",
      "                 'Convolutional layers are generally more expensive than '\n",
      "                 'recurrent layers, by a factor of k. Separable convolutions '\n",
      "                 '[6] , however, decrease the complexity considerably, to O(k '\n",
      "                 '• n • d + n • d 2 ) . Even with k = n, however, the '\n",
      "                 'complexity of a separable convolution is equal to the '\n",
      "                 'combination of a self-attention layer and a point-wise '\n",
      "                 'feed-forward layer, the approach we take in our model. As '\n",
      "                 'side benefit, self-attention could yield more interpretable '\n",
      "                 'models. We inspect attention distributions from our models '\n",
      "                 'and present and discuss examples in the appendix. Not only '\n",
      "                 'do individual attention heads clearly learn to perform '\n",
      "                 'different tasks, many appear to exhibit behavior related to '\n",
      "                 'the syntactic and semantic structure of the sentences. '\n",
      "                 'Training This section describes the training regime for our '\n",
      "                 'models. Training Data and Batching We trained on the '\n",
      "                 'standard WMT 2014 English-German dataset consisting of about '\n",
      "                 '4.5 million sentence pairs. Sentences were encoded using '\n",
      "                 'byte-pair encoding [3] , which has a shared sourcetarget '\n",
      "                 'vocabulary of about 37000 tokens. For English-French, we '\n",
      "                 'used the significantly larger WMT 2014 English-French '\n",
      "                 'dataset consisting of 36M sentences and split tokens into a '\n",
      "                 '32000 word-piece vocabulary [38] . Sentence pairs were '\n",
      "                 'batched together by approximate sequence length. Each '\n",
      "                 'training batch contained a set of sentence pairs containing '\n",
      "                 'approximately 25000 source tokens and 25000 target tokens. '\n",
      "                 'Hardware and Schedule We trained our models on one machine '\n",
      "                 'with 8 NVIDIA P100 GPUs. For our base models using the '\n",
      "                 'hyperparameters described throughout the paper, each '\n",
      "                 'training step took about 0.4 seconds. We trained the base '\n",
      "                 'models for a total of 100,000 steps or 12 hours. For our big '\n",
      "                 'models,(described on the bottom line of table 3 ), step time '\n",
      "                 'was 1.0 seconds. The big models were trained for 300,000 '\n",
      "                 'steps (3.5 days). Optimizer We used the Adam optimizer [20] '\n",
      "                 'with β 1 = 0.9, β 2 = 0.98 and = 10 −9 . We varied the '\n",
      "                 'learning rate over the course of training, according to the '\n",
      "                 'formula: lrate = d −0.5 model • min(step_num −0.5 , step_num '\n",
      "                 '• warmup_steps −1.5 ) (3) This corresponds to increasing the '\n",
      "                 'learning rate linearly for the first warmup_steps training '\n",
      "                 'steps, and decreasing it thereafter proportionally to the '\n",
      "                 'inverse square root of the step number. We used warmup_steps '\n",
      "                 '= 4000. Regularization We employ three types of '\n",
      "                 'regularization during training: Residual Dropout We apply '\n",
      "                 'dropout [33] to the output of each sub-layer, before it is '\n",
      "                 'added to the sub-layer input and normalized. In addition, we '\n",
      "                 'apply dropout to the sums of the embeddings and the '\n",
      "                 'positional encodings in both the encoder and decoder stacks. '\n",
      "                 'For the base model, we use a rate of P drop = 0.1. Label '\n",
      "                 'Smoothing During training, we employed label smoothing of '\n",
      "                 'value ls = 0.1 [36] . This hurts perplexity, as the model '\n",
      "                 'learns to be more unsure, but improves accuracy and BLEU '\n",
      "                 'score. 6 Results Machine Translation On the WMT 2014 '\n",
      "                 'English-to-German translation task, the big transformer '\n",
      "                 'model (Transformer (big) in Table 2 ) outperforms the best '\n",
      "                 'previously reported models (including ensembles) by more '\n",
      "                 'than 2.0 BLEU, establishing a new state-of-the-art BLEU '\n",
      "                 'score of 28.4. The configuration of this model is listed in '\n",
      "                 'the bottom line of Table 3 . Training took 3.5 days on 8 '\n",
      "                 'P100 GPUs. Even our base model surpasses all previously '\n",
      "                 'published models and ensembles, at a fraction of the '\n",
      "                 'training cost of any of the competitive models. On the WMT '\n",
      "                 '2014 English-to-French translation task, our big model '\n",
      "                 'achieves a BLEU score of 41.0, outperforming all of the '\n",
      "                 'previously published single models, at less than 1/4 the '\n",
      "                 'training cost of the previous state-of-the-art model. The '\n",
      "                 'Transformer (big) model trained for English-to-French used '\n",
      "                 'dropout rate P drop = 0.1, instead of 0.3. For the base '\n",
      "                 'models, we used a single model obtained by averaging the '\n",
      "                 'last 5 checkpoints, which were written at 10-minute '\n",
      "                 'intervals. For the big models, we averaged the last 20 '\n",
      "                 'checkpoints. We used beam search with a beam size of 4 and '\n",
      "                 'length penalty α = 0.6 [38] . These hyperparameters were '\n",
      "                 'chosen after experimentation on the development set. We set '\n",
      "                 'the maximum output length during inference to input length + '\n",
      "                 '50, but terminate early when possible [38] . Model '\n",
      "                 'Variations To evaluate the importance of different '\n",
      "                 'components of the Transformer, we varied our base model in '\n",
      "                 'different ways, measuring the change in performance on '\n",
      "                 'English-to-German translation on the development set, '\n",
      "                 'newstest2013. We used beam search as described in the '\n",
      "                 'previous section, but no checkpoint averaging. We present '\n",
      "                 'these results in Table 3 . In Table 3 rows (A), we vary the '\n",
      "                 'number of attention heads and the attention key and value '\n",
      "                 'dimensions, keeping the amount of computation constant, as '\n",
      "                 'described in Section 3.2.2. While single-head attention is '\n",
      "                 '0.9 BLEU worse than the best setting, quality also drops off '\n",
      "                 'with too many heads. In Table 3 rows (B), we observe that '\n",
      "                 'reducing the attention key size d k hurts model quality. '\n",
      "                 'This suggests that determining compatibility is not easy and '\n",
      "                 'that a more sophisticated compatibility function than dot '\n",
      "                 'product may be beneficial. We further observe in rows (C) '\n",
      "                 'and (D) that, as expected, bigger models are better, and '\n",
      "                 'dropout is very helpful in avoiding over-fitting. In row (E) '\n",
      "                 'we replace our sinusoidal positional encoding with learned '\n",
      "                 'positional embeddings [9] , and observe nearly identical '\n",
      "                 'results to the base model. English Constituency Parsing To '\n",
      "                 'evaluate if the Transformer can generalize to other tasks we '\n",
      "                 'performed experiments on English constituency parsing. This '\n",
      "                 'task presents specific challenges: the output is subject to '\n",
      "                 'strong structural constraints and is significantly longer '\n",
      "                 'than the input. Furthermore, RNN sequence-to-sequence models '\n",
      "                 'have not been able to attain state-of-the-art results in '\n",
      "                 'small-data regimes [37] . We trained a 4-layer transformer '\n",
      "                 'with d model = 1024 on the Wall Street Journal (WSJ) portion '\n",
      "                 'of the Penn Treebank [25] , about 40K training sentences. We '\n",
      "                 'also trained it in a semi-supervised setting, using the '\n",
      "                 'larger high-confidence and BerkleyParser corpora from with '\n",
      "                 'approximately 17M sentences [37] . We used a vocabulary of '\n",
      "                 '16K tokens for the WSJ only setting and a vocabulary of 32K '\n",
      "                 'tokens for the semi-supervised setting. We performed only a '\n",
      "                 'small number of experiments to select the dropout, both '\n",
      "                 'attention and residual (section 5.4), learning rates and '\n",
      "                 'beam size on the Section 22 development set, all other '\n",
      "                 'parameters remained unchanged from the English-to-German '\n",
      "                 'base translation model. During inference, we increased the '\n",
      "                 'maximum output length to input length + 300. We used a beam '\n",
      "                 'size of 21 and α = 0.3 for both WSJ only and the '\n",
      "                 'semi-supervised setting. Our results in Table 4 show that '\n",
      "                 'despite the lack of task-specific tuning our model performs '\n",
      "                 'surprisingly well, yielding better results than all '\n",
      "                 'previously reported models with the exception of the '\n",
      "                 'Recurrent Neural Network Grammar [8] . In contrast to RNN '\n",
      "                 'sequence-to-sequence models [37] , the Transformer '\n",
      "                 'outperforms the Berkeley-Parser [29] even when training only '\n",
      "                 'on the WSJ training set of 40K sentences. Conclusion In this '\n",
      "                 'work, we presented the Transformer, the first sequence '\n",
      "                 'transduction model based entirely on attention, replacing '\n",
      "                 'the recurrent layers most commonly used in encoder-decoder '\n",
      "                 'architectures with multi-headed self-attention. For '\n",
      "                 'translation tasks, the Transformer can be trained '\n",
      "                 'significantly faster than architectures based on recurrent '\n",
      "                 'or convolutional layers. On both WMT 2014 English-to-German '\n",
      "                 'and WMT 2014 English-to-French translation tasks, we achieve '\n",
      "                 'a new state of the art. In the former task our best model '\n",
      "                 'outperforms even all previously reported ensembles. We are '\n",
      "                 'excited about the future of attention-based models and plan '\n",
      "                 'to apply them to other tasks. We plan to extend the '\n",
      "                 'Transformer to problems involving input and output '\n",
      "                 'modalities other than text and to investigate local, '\n",
      "                 'restricted attention mechanisms to efficiently handle large '\n",
      "                 'inputs and outputs such as images, audio and video. Making '\n",
      "                 'generation less sequential is another research goals of '\n",
      "                 'ours. The code we used to train and evaluate our models is '\n",
      "                 'available at https://github.com/ tensorflow/tensor2tensor. '\n",
      "                 'Attention Visualizations Input-Input Layer5 Acknowledgements '\n",
      "                 'We are grateful to Nal Kalchbrenner and Stephan Gouws for '\n",
      "                 'their fruitful comments, corrections and inspiration. '\n",
      "                 'Input-Input Layer5 The Input-Input Layer5 The',\n",
      " 'article_title': 'Attention Is All You Need',\n",
      " 'article_url': 'https://arxiv.org/pdf/1706.03762.pdf',\n",
      " 'summary': [' We propose a new simple network architecture, the Transformer, '\n",
      "             'based solely on attention mechanisms. Experiments on two machine '\n",
      "             'translation tasks show these models to be superior in quality '\n",
      "             'while being more parallelizable and requiring significantly less '\n",
      "             'time to train. The Transformer allows for significantly more '\n",
      "             'parallelization and can reach a new state-of-the-art in '\n",
      "             'translation quality after being trained for as little as twelve '\n",
      "             'hours on eight P100 GPUs. The goal of reducing sequential '\n",
      "             'computation also forms the foundation of the Extended Neural GPU '\n",
      "             '[16], ByteNet [18] and ConvS2S.']}\n"
     ]
    }
   ],
   "source": [
    "url = \"https://tldrthis.p.rapidapi.com/v1/model/abstractive/summarize-url/\"\n",
    "\n",
    "payload = {\n",
    "    \"url\": \"https://arxiv.org/pdf/1706.03762.pdf\", # 주소\n",
    "    \"min_length\": 100, # 최소 길이\n",
    "    \"max_length\": 300, # 최대 길이\n",
    "    \"is_detailed\": False # 한 문장으로 반환할 것인지 여부\n",
    "}\n",
    "\n",
    "headers = {\n",
    "    \"content-type\": \"application/json\",\n",
    "    \"X-RapidAPI-Key\": rapidapi_key,\n",
    "    \"X-RapidAPI-Host\": \"tldrthis.p.rapidapi.com\"\n",
    "}\n",
    "\n",
    "response = requests.request(\"POST\", url, json=payload, headers=headers)\n",
    "\n",
    "pprint(response.json())"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 30,
   "id": "a9911dfa",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "We propose a new simple network architecture, the Transformer, based solely on attention mechanisms. Experiments on two machine translation tasks show these models to be superior in quality while being more parallelizable and requiring significantly less time to train. The Transformer allows for significantly more parallelization and can reach a new state-of-the-art in translation quality after being trained for as little as twelve hours on eight P100 GPUs. The goal of reducing sequential computation also forms the foundation of the Extended Neural GPU [16], ByteNet [18] and ConvS2S.\n"
     ]
    }
   ],
   "source": [
    "summary = response.json()['summary'][0].strip()\n",
    "\n",
    "print(summary)"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "142c4aa4",
   "metadata": {},
   "source": [
    "## 번역\n",
    "\n",
    "네이버 파파고 API"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 31,
   "id": "8bc6a8ee",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "{'message': {'@service': 'naverservice.nmt.proxy',\n",
      "             '@type': 'response',\n",
      "             '@version': '1.0.0',\n",
      "             'result': {'dict': None,\n",
      "                        'engineType': 'UNDEF_MULTI_SENTENCE',\n",
      "                        'pivot': None,\n",
      "                        'srcLangType': 'en',\n",
      "                        'tarDict': None,\n",
      "                        'tarLangType': 'ko',\n",
      "                        'translatedText': '우리는 주의 메커니즘만을 기반으로 하는 새로운 간단한 네트워크 '\n",
      "                                          '아키텍처인 트랜스포머를 제안한다. 두 가지 기계 번역 작업에 '\n",
      "                                          '대한 실험은 이러한 모델이 품질 면에서 우수하면서도 병렬화가 더 '\n",
      "                                          '가능하고 교육하는 데 훨씬 적은 시간이 필요하다는 것을 '\n",
      "                                          '보여준다. Transformer는 훨씬 더 많은 병렬화를 '\n",
      "                                          '가능하게 하며 8개의 P100 GPU에서 12시간 정도 교육을 '\n",
      "                                          '받은 후 번역 품질에서 새로운 최첨단 기술에 도달할 수 '\n",
      "                                          '있습니다. 순차 연산을 줄이는 목표는 확장 신경 GPU[16], '\n",
      "                                          'ByteNet[18] 및 ConvS2S의 기초를 형성한다.'}}}\n"
     ]
    }
   ],
   "source": [
    "url = \"https://openapi.naver.com/v1/papago/n2mt\"\n",
    "\n",
    "payload = {\n",
    "    \"source\": \"en\",\n",
    "    \"target\": \"ko\",\n",
    "    \"text\": summary,\n",
    "}\n",
    "\n",
    "headers = {\n",
    "    \"content-type\": \"application/json\",\n",
    "    \"X-Naver-Client-Id\": naver_client_id,\n",
    "    \"X-Naver-Client-Secret\": naver_client_secret,\n",
    "}\n",
    "\n",
    "response = requests.request(\"POST\", url, json=payload, headers=headers)\n",
    "\n",
    "pprint(response.json())"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 32,
   "id": "e204b577",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "우리는 주의 메커니즘만을 기반으로 하는 새로운 간단한 네트워크 아키텍처인 트랜스포머를 제안한다. 두 가지 기계 번역 작업에 대한 실험은 이러한 모델이 품질 면에서 우수하면서도 병렬화가 더 가능하고 교육하는 데 훨씬 적은 시간이 필요하다는 것을 보여준다. Transformer는 훨씬 더 많은 병렬화를 가능하게 하며 8개의 P100 GPU에서 12시간 정도 교육을 받은 후 번역 품질에서 새로운 최첨단 기술에 도달할 수 있습니다. 순차 연산을 줄이는 목표는 확장 신경 GPU[16], ByteNet[18] 및 ConvS2S의 기초를 형성한다.\n"
     ]
    }
   ],
   "source": [
    "print(response.json()['message']['result']['translatedText'])"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "df0b8837",
   "metadata": {},
   "source": [
    "## 함수화"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 48,
   "id": "3ef2e310",
   "metadata": {},
   "outputs": [],
   "source": [
    "def summarize_and_translate(article_url, min_length=100, max_length=300):\n",
    "    url = \"https://tldrthis.p.rapidapi.com/v1/model/abstractive/summarize-url/\"\n",
    "\n",
    "    payload = {\n",
    "        \"url\": article_url, # 주소\n",
    "        \"min_length\": min_length, # 최소 길이\n",
    "        \"max_length\": max_length, # 최대 길이\n",
    "        \"is_detailed\": False # 한 문장으로 반환할 것인지 여부\n",
    "    }\n",
    "\n",
    "    headers = {\n",
    "        \"content-type\": \"application/json\",\n",
    "        \"X-RapidAPI-Key\": rapidapi_key,\n",
    "        \"X-RapidAPI-Host\": \"tldrthis.p.rapidapi.com\"\n",
    "    }\n",
    "\n",
    "    response = requests.request(\"POST\", url, json=payload, headers=headers)\n",
    "\n",
    "    summary = response.json()['summary'][0].strip()\n",
    "    \n",
    "    url = \"https://openapi.naver.com/v1/papago/n2mt\"\n",
    "\n",
    "    payload = {\n",
    "        \"source\": \"en\",\n",
    "        \"target\": \"ko\",\n",
    "        \"text\": summary,\n",
    "    }\n",
    "\n",
    "    headers = {\n",
    "        \"content-type\": \"application/json\",\n",
    "        \"X-Naver-Client-Id\": naver_client_id,\n",
    "        \"X-Naver-Client-Secret\": naver_client_secret\n",
    "    }\n",
    "\n",
    "    response = requests.request(\"POST\", url, json=payload, headers=headers)\n",
    "    \n",
    "    return response.json()['message']['result']['translatedText']"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 50,
   "id": "88afea5a",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "'우리는 주의 메커니즘만을 기반으로 하는 새로운 간단한 네트워크 아키텍처인 트랜스포머를 제안한다. 두 가지 기계 번역 작업에 대한 실험은 이러한 모델이 품질 면에서 우수하면서도 병렬화가 더 가능하고 교육하는 데 훨씬 적은 시간이 필요하다는 것을 보여준다. 트랜스포머는 훨씬 더 많은 병렬화를 가능하게 하며 8개의 P100에서 12시간 동안만 교육을 받은 후 번역 품질에서 새로운 기술에 도달할 수 있습니다.'"
      ]
     },
     "execution_count": 50,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "summarize_and_translate(\"https://arxiv.org/pdf/1706.03762.pdf\", 50, 100)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 51,
   "id": "52a35173",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "'EfficientNet-B7은 ImageNet에서 최고 84.3%의 정확도를 달성하는 동시에 기존 최고의 ConvNet보다 8.4배 작고 추론 속도가 6.1배 빠르다. 우리의 EfficientNets는 다른 ConvNets를 크게 능가한다. 이전 작업에서는 깊이, 너비, 이미지 크기 등 세 가지 차원 중 하나만 스케일링하는 것이 일반적이다. 단순하지만 매우 효과적인 복합 계수를 사용하여 깊이/폭/해상도의 모든 차원을 균일하게 확장하는 단순하지만 효과적인 복합 스케일링 방법을 제안한다. 예를 들어, 우리가 2N배 더 많은 계산 자원을 사용하고 싶다면, 우리는 단순히 원래 모델에서 네트워크를 작은 그리드만큼 늘릴 수 있다.'"
      ]
     },
     "execution_count": 51,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "summarize_and_translate(\"https://arxiv.org/pdf/1905.11946.pdf\", 100, 200)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "286fefce",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.8.5"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
